/**
 * Via Deployment Artifact Types
 *
 * These types define the shape of the deployment artifact JSON files
 * (via.deployments.testnet.json / via.deployments.mainnet.json).
 *
 * The deployment artifact is the single source of truth for all contract
 * addresses and the zkSync pair bytecode hash used by the UI.
 * It is generated by the via-contracts deployment scripts and checked
 * into this repo so the UI can load addresses synchronously at startup.
 *
 * After deploying contracts, update the corresponding JSON file with
 * the real addresses and pairBytecodeHash from the deployment output.
 */

/** Supported Via chain IDs */
export type ViaChainId = 25223 | 5223

/** Addresses and bytecode hash for the Uniswap V2 deployment on Via */
export interface ViaUniswapV2Deployment {
  /** UniswapV2Router02 address (0x-prefixed, checksummed) */
  router02: string
  /** UniswapV2Factory address (0x-prefixed, checksummed) */
  factory: string
  /** WBTC (wrapped native BTC) address (0x-prefixed, checksummed) */
  wbtc: string
  /** Multicall contract address — must support legacy aggregate() ABI */
  multicall: string
  /**
   * zkSync-format bytecode hash (e.g. 0x0100...) for UniswapV2Pair.
   * Used by create2Address() to deterministically compute pair addresses.
   * This MUST match the actual deployed Pair bytecode produced by zksolc.
   */
  pairBytecodeHash: string
}

/** Full deployment artifact for a single Via network */
export interface ViaDeploymentArtifact {
  /** Chain ID this artifact is for (must match runtime chainId) */
  chainId: ViaChainId
  /** JSON-RPC URL for this network */
  rpcUrl: string
  /** Optional block explorer base URL (e.g. Blockscout) */
  explorerBaseUrl?: string
  /** Contract deployments grouped by protocol version */
  contracts: {
    v2: ViaUniswapV2Deployment
    // Reserved for future protocol versions:
    // v4?: ViaDexV4Deployment
  }
  /** Deployment metadata for traceability */
  meta: {
    /** ISO timestamp of when contracts were deployed */
    deployedAt: string
    /** Git commit hash from the contracts repo at deploy time */
    gitCommit: string
    /** Compiler versions used */
    compiler: {
      solc: string
      zksolc: string
    }
  }
}
